### ISSUE TITLE
 No module named ordinal_decode_layer

### ISSUE THREAD

**Issue by beginnerFighting** [hufu6371/DORN#19]
Hi, thanks to your awesome work. When I try test demo.py, it shows:

ImportError: No module named ordinal_decode_layer

 I make successfully pycaffe.

**Comment by qq664956261** [comment]
cloud you tell me how to solve this question? @beginnerFighting

**Comment by isgursoy** [comment]
`$ export PYTHONPATH=$PYTHONPATH:/yourPath/`
Your path is DORN/caffe/pylayer which has "ordinal_decode_layer.py" in this case. You can move that file anywhere you want. You can google for making environment variable persistent.
