### ISSUE TITLE
Ordinal Regression in cpp

### ISSUE THREAD

**Issue by isgursoy** [hufu6371/DORN#27]
What makes your python layer difference from https://github.com/luoyetx/OrdinalRegression ?

**Comment by rauldiaz** [comment]
Without reading the cpp code, but having read both papers, I think the layers are the same in some sense. They classify ranks (age or depth) based on binary classifiers for each of the ranks. The only difference is that the age estimation paper does this image-wise, and DORN does the same pixel-wise.

**Comment by isgursoy** [comment]
Thanks for explanation.
