### ISSUE TITLE
KITTI model clarification

### ISSUE THREAD

**Issue by a-jahani** [hufu6371/DORN#4]
Hi,

thanks for sharing. Does kitti model uses kitti depth dataset for training ? or it uses the Eigen split? or it is the model you used for Robust vision challenge? 
If not is it possible to share Eigen model you evaluated in the paper and also Robust vision challenge pretrained model aswell?

Thanks

**Comment by hufu6371** [comment]
Pls. see our introduction.  This shared model is trained on the Eigen split. 
Sorry, we are not allowed to share the pertained models for Robust Vision Challenge 2018 now.
