### ISSUE TITLE
Why is 2K?

### ISSUE THREAD

**Issue by Mrils** [hufu6371/DORN#6]
Hello! Thanks for your outstanding work! But i have some questions about your paper.
When i read your paper, i wonder why the number of Y is 2K. And what's the double layers in Ordinal regression stand for?

**Comment by ziqi-zhang** [comment]
I think for the kth threshold (i.e. tk in the paper), the net needs one value(2k) representing the passibility at which a point's depth value is greater than it and another value(2k+1) representing the possibility at which the point's depth value is less that it. And the final possibility is the softmax of these two values. So given K bins, it needs 2K values, which needs 2K classifiers.

**Comment by hufu6371** [comment]
@Mrils Thanks @ziqi-zhang .

**Comment by Usernamezhx** [comment]
@ziqi-zhang  I have a little confusion about the paper. where to apply the SID ? to the ground truth depth label ? or the feature map produced by  net ?

**Comment by hufu6371** [comment]
Hi, Zhang,


The SID is used to obtain some discrete labels from the ground-truth labels.

May be K would be a good choice, but we only study DORN based 2K.


Best,

Huan

________________________________
