### ISSUE TITLE
No module named 'ordinal_decode_layer', any ideas?

### ISSUE THREAD

**Issue by myopengit** [hufu6371/DORN#9]
I0627 14:09:56.936329  3141 layer_factory.hpp:77] Creating layer decode_ord
ImportError: No module named 'ordinal_decode_layer'
Traceback (most recent call last):
  File "demo_nyuv2.py", line 15, in <module>
    net = caffe.Net('models/NYUV2/deploy.prototxt', 'models/NYUV2/cvpr_nyuv2.caffemodel', caffe.TEST)
SystemError: <Boost.Python.function object at 0x1d53a50> returned NULL without setting an error

**Comment by myopengit** [comment]
I am using the provided caffe

**Comment by mbaradad** [comment]
You need to uncomment the line 
WITH_PYTHON_LAYER := 1
after copying Make.config.example to Makefile.config
